apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing101
  labels:
    app: testing101
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing101
  template:
    metadata:
      labels:
        app: testing101
    spec:
      containers:
        - name: testing101
          image: ghcr.io/mb-wali/coming-soon:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: TOOL_NAME
              value: "MY New Tool in kubernetes"
            - name: DEADLINE
              value: "June 30, 2026"
            - name: LOGO_NAME
              value: "logo.svg"
